# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Visit.destroy_all
ShortenedUrl.destroy_all
User.destroy_all

u1 = User.create!(email: 'abc@d.c')
u2 = User.create!(email: 'def@com.net')
u3 = User.create!(email: 'ghi@gm.hi')
u4 = User.create!(email: 'jk@lol.bbq')
u5 = User.create!(email: 'idk@irl.lmao')

s1 = ShortenedUrl.make_shortened_url!(long_url: 'google.com', user: u1)
s2 = ShortenedUrl.make_shortened_url!(long_url: 'google.com', user: u2)
s3 = ShortenedUrl.make_shortened_url!(long_url: 'amazon.com', user: u3)
s4 = ShortenedUrl.make_shortened_url!(long_url: 'appacademy.io', user: u4)
s5 = ShortenedUrl.make_shortened_url!(long_url: 'apple.com', user: u5)
s6 = ShortenedUrl.make_shortened_url!(long_url: 'facebook.com', user: u1)
s7 = ShortenedUrl.make_shortened_url!(long_url: 'twitter.com', user: u2)
s8 = ShortenedUrl.make_shortened_url!(long_url: 'reddit.com', user: u3)
s9 = ShortenedUrl.make_shortened_url!(long_url: 'twitter.com', user: u4)
s10 = ShortenedUrl.make_shortened_url!(long_url: 'riotgames.com', user: u5)

v1 = Visit.record_visit!(user: u1, shortened_url: s1)
v1 = Visit.record_visit!(user: u2, shortened_url: s2)
v1 = Visit.record_visit!(user: u3, shortened_url: s2)
v1 = Visit.record_visit!(user: u4, shortened_url: s2)
v1 = Visit.record_visit!(user: u5, shortened_url: s2)
v1 = Visit.record_visit!(user: u1, shortened_url: s4)
v1 = Visit.record_visit!(user: u2, shortened_url: s4)
v1 = Visit.record_visit!(user: u3, shortened_url: s4)
v1 = Visit.record_visit!(user: u2, shortened_url: s4)
v1 = Visit.record_visit!(user: u3, shortened_url: s4)
v1 = Visit.record_visit!(user: u4, shortened_url: s4)
v1 = Visit.record_visit!(user: u5, shortened_url: s4)
v1 = Visit.record_visit!(user: u1, shortened_url: s3)
v1 = Visit.record_visit!(user: u2, shortened_url: s2)
v1 = Visit.record_visit!(user: u3, shortened_url: s3)
v1 = Visit.record_visit!(user: u4, shortened_url: s3)
v1 = Visit.record_visit!(user: u5, shortened_url: s4)
v1 = Visit.record_visit!(user: u1, shortened_url: s3)
v1 = Visit.record_visit!(user: u2, shortened_url: s3)
v1 = Visit.record_visit!(user: u1, shortened_url: s3)
v1 = Visit.record_visit!(user: u2, shortened_url: s5)
v1 = Visit.record_visit!(user: u3, shortened_url: s5)
v1 = Visit.record_visit!(user: u4, shortened_url: s5)
v1 = Visit.record_visit!(user: u5, shortened_url: s5)

v1 = Visit.record_visit!(user: u1, shortened_url: s6)
v1 = Visit.record_visit!(user: u2, shortened_url: s7)
v1 = Visit.record_visit!(user: u3, shortened_url: s7)
v1 = Visit.record_visit!(user: u4, shortened_url: s7)
v1 = Visit.record_visit!(user: u5, shortened_url: s7)
v1 = Visit.record_visit!(user: u1, shortened_url: s8)
v1 = Visit.record_visit!(user: u2, shortened_url: s8)
v1 = Visit.record_visit!(user: u3, shortened_url: s8)
v1 = Visit.record_visit!(user: u2, shortened_url: s8)
v1 = Visit.record_visit!(user: u3, shortened_url: s8)
v1 = Visit.record_visit!(user: u4, shortened_url: s8)
v1 = Visit.record_visit!(user: u5, shortened_url: s8)
v1 = Visit.record_visit!(user: u1, shortened_url: s9)
v1 = Visit.record_visit!(user: u2, shortened_url: s7)
v1 = Visit.record_visit!(user: u3, shortened_url: s9)
v1 = Visit.record_visit!(user: u4, shortened_url: s9)
v1 = Visit.record_visit!(user: u5, shortened_url: s8)
v1 = Visit.record_visit!(user: u1, shortened_url: s9)
v1 = Visit.record_visit!(user: u2, shortened_url: s9)
v1 = Visit.record_visit!(user: u1, shortened_url: s9)
v1 = Visit.record_visit!(user: u2, shortened_url: s10)
v1 = Visit.record_visit!(user: u3, shortened_url: s10)
v1 = Visit.record_visit!(user: u4, shortened_url: s10)
v1 = Visit.record_visit!(user: u5, shortened_url: s10)
